/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:d395af6f-bef8-450e-89c1-3a7d8a46d924",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_xMxOKJhrj",
    "aws_user_pools_web_client_id": "4massl4jm6221jglrtpl28jltj",
    "oauth": {}
};


export default awsmobile;
